config {
  type: "incremental",
  schema: "BI",
  name: "profiling_dashboard_quick_win_TEST",
  tags: ["dashboard", "diario"],
  uniqueKey: ["lead_id"],
  description: "Tabla consolidada incremental. Actualiza leads existentes e inserta nuevos.",
  bigquery: {
    partitionBy: "DATE(Fecha_creacion)",
  }
}

WITH
-- 1. Staging de Profiling
stg_profiling AS (
  SELECT
    id AS lead_id,
    createdAt as Fecha_creacion,
    fullname,
    builderKey as Constructora,
    identification,
    gender,
    venta_efectiva,
    createdEmail,
    qualification AS calificacion_sugerida,
    ACTIVIDAD_ECONOMICA AS ocupacion,
    rol,
    document_id,
    VALOR_INGRESO_FINAL AS ingresos,
    propertyDelivery AS fecha_entrega_proyecto,
    financeValue AS valor_a_financiar,
    projectCity as ciudad_proyecto,
    projectName AS nombre_proyecto,
    propertyType AS tipo_vivienda,
    propertyValue as valor_vivienda,
    preselectaScore AS score,
    preselectaDecision,
    preselectaStatus,
    scoring,
    score_date,
    INGRESO_FINAL,
    ENDEUDAMIENTO,
    sarlaftStatus,
    identificationStatus,
    CUOTAS_TITULAR,
    housingLawIndicator,
    idFamilyGroup
  FROM ${ref("tbl_profiling_TEST")}
),

-- 2. Staging de la Calculadora Individual
stg_calculator AS (
  SELECT
    id_lead, rango_salarios, rango_endeudamiento, rango_score, rango_credito_max_pesos_15,
    rango_credito_max_uvr_15, rango_credito_max_pesos_20, rango_credito_max_uvr_20,
    rango_credito_max_uvr_30, valor_credito, valor_credito_pesos_20_anios,
    valor_credito_uvr_20_anios, valor_credito_uvr_30_anios, credito_maximo_segun_disponible_pesos,
    credito_maximo_segun_disponible_uvr, endeudamiento
  FROM ${ref("Calculator_table")}
  QUALIFY ROW_NUMBER() OVER(PARTITION BY id_lead ORDER BY timestamp_registro DESC) = 1
),

-- 3. Staging de la Calculadora Familiar
stg_calculator_fam AS (
  SELECT
    id_lead, idFamilyGroup, document_id, rango_salarios, rango_endeudamiento, rango_score, rango_credito_max_pesos_15,
    rango_credito_max_uvr_15, rango_credito_max_pesos_20, rango_credito_max_uvr_20,
    rango_credito_max_uvr_30, valor_credito, valor_credito_pesos_20_anios,
    valor_credito_uvr_20_anios, valor_credito_uvr_30_anios, credito_maximo_segun_disponible_pesos,
    credito_maximo_segun_disponible_uvr, calificacion, koggi_profiling, indicador_ley_vivienda, ingresos, maximo_cuota_ley_vivienda,
    cuotas_titular, gastos_familiares
  FROM ${ref("src_calculator_fam")} 
  QUALIFY ROW_NUMBER() OVER(PARTITION BY id_lead ORDER BY timestamp_registro DESC) = 1
),

-- 4. CTE para usuarios únicos
usuarios_unicos AS (
  SELECT id, email, entity_key, name, id_group,
    ROW_NUMBER() OVER(PARTITION BY email, entity_key ORDER BY id) as rn
  FROM ${ref("tbl_user")}
),

-- 5. CTE para grupos de usuarios
grupos_usuarios AS (
  SELECT u.email, u.entity_key, u.name AS usuario_nombre, g.name AS tipo_usuario, g.observation as observacion
  FROM usuarios_unicos u
  LEFT JOIN ${ref("tbl_groups")} g ON u.id_group = g.id
  WHERE u.rn = 1
),

-- 6. Ensamble Final
quick_win_source_data AS (
  SELECT
    p.lead_id,
    p.identification,
    p.Fecha_creacion,
    p.createdEmail,
    p.fullname,
    age.edad_promedio,
    p.gender,
    p.rol,
    p.document_id,
    p.ocupacion,
    usr.usuario_nombre,
    usr.tipo_usuario,
    usr.observacion,
    p.idFamilyGroup,
    p.Constructora,
    p.nombre_proyecto,
    p.ciudad_proyecto,
    p.tipo_vivienda,
    p.valor_vivienda,
    p.fecha_entrega_proyecto,
    p.calificacion_sugerida,
    p.score,
    p.scoring,
    p.score_date,
    p.preselectaDecision,
    p.preselectaStatus,
    p.ingresos,
    p.INGRESO_FINAL,
    p.ENDEUDAMIENTO,
    p.CUOTAS_TITULAR,
    p.sarlaftStatus,
    p.identificationStatus,
    p.housingLawIndicator,
    p.venta_efectiva,

    -- Campos de Calculadora Individual
    COALESCE(c.rango_salarios, 'Sin Información') AS rango_salarios,
    COALESCE(c.rango_endeudamiento, 'Sin Información') AS rango_endeudamiento,
    COALESCE(c.rango_score, 'Sin Información') AS rango_score,
    COALESCE(c.rango_credito_max_pesos_15, 'Sin Información') AS rango_credito_max_pesos_15,
    COALESCE(c.rango_credito_max_uvr_15, 'Sin Información') AS rango_credito_max_uvr_15,
    COALESCE(c.rango_credito_max_pesos_20, 'Sin Información') AS rango_credito_max_pesos_20,
    COALESCE(c.rango_credito_max_uvr_20, 'Sin Información') AS rango_credito_max_uvr_20,
    COALESCE(c.rango_credito_max_uvr_30, 'Sin Información') AS rango_credito_max_uvr_30,

    -- Campos de Calculadora Familiar
    COALESCE(cfam.calificacion, 'Sin Información') as fam_calificacion,
    COALESCE(cfam.rango_endeudamiento, 'Sin Información') as fam_rango_endeudamiento,
    COALESCE(cfam.koggi_profiling, 'Sin Información') as fam_koggi_profiling,
    COALESCE(cfam.indicador_ley_vivienda, 'Sin Información') as fam_indicador_ley_vivienda,
    cfam.ingresos AS fam_ingresos,
    cfam.cuotas_titular AS fam_cuotas_titular,
    cfam.gastos_familiares AS fam_gastos_familiares,
    COALESCE(cfam.rango_salarios, 'Sin Información') as fam_rangos_salarios,
    COALESCE(cfam.rango_score, 'Sin Información') as fam_rango_score,
    COALESCE(cfam.rango_credito_max_pesos_15, 'Sin Información') as fam_rango_credito_max_pesos_15,
    COALESCE(cfam.rango_credito_max_uvr_15, 'Sin Información') AS fam_rango_credito_max_uvr_15,
    COALESCE(cfam.rango_credito_max_pesos_20, 'Sin Información') AS fam_rango_credito_max_pesos_20,
    COALESCE(cfam.rango_credito_max_uvr_20, 'Sin Información') AS fam_rango_credito_max_uvr_20,
    COALESCE(cfam.rango_credito_max_uvr_30, 'Sin Información') AS fam_rango_credito_max_uvr_30,

    p.valor_a_financiar,
    c.valor_credito,
    c.valor_credito_pesos_20_anios,
    c.valor_credito_uvr_20_anios,
    c.valor_credito_uvr_30_anios,
    c.credito_maximo_segun_disponible_pesos,
    c.credito_maximo_segun_disponible_uvr,
    look.uid_entity AS uid_looker,

    CASE
      WHEN p.idFamilyGroup IS NOT NULL THEN 'GRUPO FAMILIAR'
      ELSE 'ÚNICO COMPRADOR'
    END AS unidades_vivienda

  FROM stg_profiling AS p
  LEFT JOIN ${ref("stg_hdc_parsed_age_TEST")} AS age ON p.identification = age.identificacion
  LEFT JOIN stg_calculator AS c ON p.lead_id = c.id_lead
  LEFT JOIN stg_calculator_fam as cfam ON p.idFamilyGroup = cfam.idFamilyGroup
  LEFT JOIN grupos_usuarios AS usr ON p.createdEmail = usr.email AND p.Constructora = usr.entity_key
  LEFT JOIN ${ref("tbl_entity_database")} AS ent ON p.Constructora = ent.key
  LEFT JOIN ${ref("tbl_looker_board")} AS look ON ent.id_entity_database = look.entity_id
)

-- 7. Selección Final
SELECT
  t.*,
  TO_HEX(MD5(TO_JSON_STRING(t))) AS fila_hash,
  CURRENT_DATETIME('America/Bogota') AS fecha_ultima_actualizacion_bi
FROM quick_win_source_data AS t